from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SCICSessionProtocol(Protocol):
    @property
    def context_path(self) -> str: ...

    @property
    def context(self) -> Any: ...

    async def execute(self, instruction: str) -> list[Any]: ...

    def back(self) -> Any: ...

    def reset(self) -> Any: ...

    def describe(self, instruction: str | None = None) -> dict[str, Any]: ...

    def list_context(self) -> tuple[dict[str, Any], ...]: ...


@runtime_checkable
class SCICProtocol(Protocol):
    @property
    def root(self) -> Any: ...

    def create_session(self) -> SCICSessionProtocol: ...

    def export_tree(self) -> dict[str, Any]: ...
